### PR TITLE
Fix newline characters and punctuation

### PR DESCRIPTION
**Pull request by Tina-otoge**
Through my first playthrough of the game I used your translation and fixed some very noticeable mistakes like misplaced newline characters.

This patch adds:
- added/moved newline characters to fit the dialogue box length
- a few punctuation fixes ("Al: try this" -> "Al, try this")
- a few grammar fixes ("it's look hard" -> "it looks hard")

I went through almost every scenes (except 2) and modified the files accordingly most of the time.
I still overlooked some of them but I think it fixes more than half of the misplaced newlines and thus brings this translation closer to completion.

### CODE REVIEW

**Review by TwinDragon — COMMENTED** [review]
I've not played the game, but how does the change in 039 look in the game, as well as 042 for putting a new line on the last word? Usually I try not to do that and have a new line in such a way that it'd make sense. But I don't know how this game renders text to know for sure.

**Comment by Antielfi** [comment]
I always try to cut around avoiding single word on a new line, but sometime the game render text with space, sometime without, sometime with double space on second and third line... I lost a good amount of time to find why since the code is always the same- but give up at some point since I wasn't find a solution in resonable time.
I always promise myself to replay the game to fix this stuff, correcting some old TL reading the new H-TL made by XenoPi (who does TL waaaaay better than me).
We can push this one and re-polish on the next run

@skielred How was the english in general? I hope was too bad on my part

**Comment by skielred** [comment]
I think a single word on a new line isn't a problem. It's not weird to read, it's actually way more natural. For example here is [ cdfb6f7#R28](https://github.com/TwinDragon/cornelica-translation/pull/72/commits/cdfb6f776e4f751dab85a50f30f5f97f07836e4e#diff-6904ab32bc7424e7fcdfd6082b1029bcR28) with and without my change.

word "thing" on a single line

word "thing" not readable

@Antielfi the translation was really nice. The lines in #55 did indeed feel weird, but tbh I expected way more Google Translate gibberish! Most of the time it felt like I was playing a real English game, aside from a few side sex scenes with partial translations or weird translations, I was able to enjoy and understand the full story without getting reminded it was a fan translation often.

**Comment by TwinDragon** [comment]
The only reason I mention it is that its sorta weird to weird when the last word is its own line, so normally when I edit things, I usually either go by the comma, or find a way to make some sense from it. But that's just a personal thing really; english is downright a weird language when one gets to the nitty gritty crap about it.

**Pull request merged**
